<?php

namespace App\Http\Requests\SalonSchedule;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class SalonScheduleStoreRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "salon_id"=>"required|exists:salons,id",
            "start"=>"required|date_format:H:i",
            "end"=>"required|date_format:H:i",
            "num_of_day"=>"in:1,2,3,4,5,7",
            "working_status"=>"integer|max:1"
        ];
    }

    /**
     * @return array
     */
    public function messages()
    {
        /*return [
            "salon_id.required"=>"F",
            "salon_id.exists"=>"salons_id exists",
            "start.required"=>"start hgjhgjhgjhg jg jhg jhg jhg ",
            "end"=>"end",
            "num_of_day"=>"num",
            "working_status"=>"working_status"
        ];*/
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function failedValidation(Validator $validator)
    {
        throw new HttpResponseException(response()->json(['ValidationError' => $validator->messages()],422));
    }
}
